export const test_durgs =
    [
        {
            "Brand": "Artesunate 120",
            "Drug": "Artesunate",
            "Strength (mg)": 60,
            "Avl Strength (mg)": "60/120",
            "Packaging Size": "1s",
            "Avl Packaging Size": "1s",
            "Packaging Type": "Vial",
            "Form": "Dry Powder",
            "Disease": "Malaria",
            "Third Party": "Yes"
        },
        {
            "Brand": "Artesunate 60",
            "Drug": "Artesunate",
            "Strength (mg)": 120,
            "Avl Strength (mg)": "60/120",
            "Packaging Size": "1s",
            "Avl Packaging Size": "1s",
            "Packaging Type": "Vial",
            "Form": "Dry Powder",
            "Disease": "Malaria",
            "Third Party": "Yes"
        },
        {
            "Brand": "Aritpro 60",
            "Drug": "Artesunate",
            "Strength (mg)": 60,
            "Avl Strength (mg)": "60/120",
            "Packaging Size": "1s",
            "Avl Packaging Size": "1s",
            "Packaging Type": "Vial",
            "Form": "Dry Powder",
            "Disease": "Malaria",
            "Third Party": "Yes"
        },
        {
            "Brand": "Aritpro 120",
            "Drug": "Artesunate",
            "Strength (mg)": 120,
            "Avl Strength (mg)": "60/120",
            "Packaging Size": "1s",
            "Avl Packaging Size": "1s",
            "Packaging Type": "Vial",
            "Form": "Dry Powder",
            "Disease": "Malaria",
            "Third Party": "Yes"
        },
        {
            "Brand": "Falcivac 60",
            "Drug": "Artesunate",
            "Strength (mg)": 60,
            "Avl Strength (mg)": "60/120",
            "Packaging Size": "1s",
            "Avl Packaging Size": "1s",
            "Packaging Type": "Vial",
            "Form": "Dry Powder",
            "Disease": "Malaria",
            "Third Party": "Yes"
        },
        {
            "Brand": "Falcivac 120",
            "Drug": "Artesunate",
            "Strength (mg)": 120,
            "Avl Strength (mg)": "60/120",
            "Packaging Size": "1s",
            "Avl Packaging Size": "1s",
            "Packaging Type": "Vial",
            "Form": "Dry Powder",
            "Disease": "Malaria",
            "Third Party": "Yes"
        },
        {
            "Brand": "Larinate 60",
            "Drug": "Artesunate",
            "Strength (mg)": 60,
            "Avl Strength (mg)": "60/120",
            "Packaging Size": "1s",
            "Avl Packaging Size": "1s",
            "Packaging Type": "Vial",
            "Form": "Dry Powder",
            "Disease": "Malaria",
            "Third Party": "Yes"
        },
        {
            "Brand": "Falcigo 60",
            "Drug": "Artesunate",
            "Strength (mg)": 60,
            "Avl Strength (mg)": "60/120",
            "Packaging Size": "1s",
            "Avl Packaging Size": "1s",
            "Packaging Type": "Vial",
            "Form": "Dry Powder",
            "Disease": "Malaria",
            "Third Party": "Yes"
        },
        {
            "Brand": "Falcigo 120",
            "Drug": "Artesunate",
            "Strength (mg)": 120,
            "Avl Strength (mg)": "60/120",
            "Packaging Size": "1s",
            "Avl Packaging Size": "1s",
            "Packaging Type": "Vial",
            "Form": "Dry Powder",
            "Disease": "Malaria",
            "Third Party": "Yes"
        },
        {
            "Brand": "Artesunate",
            "Drug": "Artesunate",
            "Strength (mg)": 100,
            "Avl Strength (mg)": "100/200",
            "Packaging Size": "10s",
            "Avl Packaging Size": "10s",
            "Packaging Type": "Blister / Alu-Alu",
            "Form": "Tablet",
            "Disease": "Malaria",
            "Third Party": "Yes"
        },
        {
            "Brand": "Artesunate",
            "Drug": "Artesunate",
            "Strength (mg)": 200,
            "Avl Strength (mg)": "100/200",
            "Packaging Size": "10s",
            "Avl Packaging Size": "10s",
            "Packaging Type": "Blister / Alu-Alu",
            "Form": "Tablet",
            "Disease": "Malaria",
            "Third Party": "Yes"
        }
    ]
